### ISSUE TITLE
Is there any way to reactivate this?

### ISSUE THREAD

**Issue by BengaloBongali** [burkemw3/syncthingfuse#14]
I consider this and Syncthing the only software worth the effort of installing it on a home server, because of their movability. I think Syncthing is only half without SyncthingFUSE or - what I'd call it - selective sync. I'd definitely work on this, if I could code. Is there another way to reactivate this project? Syncthing with a selective sync option or Syncthing and SyncthingFUSE on all my devices would the shit!

**Comment by burkemw3** [comment]
Glad to see your interested in SyncthingFUSE.

I would like to get back to this, but the earliest I do will likely be March 2017.

You could plead with existing devs and/or offer a bounty to get things working again. I will review and accept pull requests.

---

As of today, getting things working again likely consists of (1) building successfully (after many changes in syncthing, which this depends on) and (2) any work necessary to switch to proto3 based BEP (which might be covered by (1)).

For a longer term solution, it may be better to plumb the GET /rest/db/file request into syncthing as mentioned in [this forum discussion](https://forum.syncthing.net/t/should-syncthingfuse-be-merged-into-syncthing/). Then, adapt clients to (e.g. SyncthingFUSE) to use that API. I predict this is much more work than getting things working again.

**Comment by burkemw3** [comment]
This is back in business, much earlier than I expected!

I've tested with 0.14.13 and made a [new release](https://github.com/burkemw3/syncthingfuse/releases/tag/v0.1.0-rc0)!

**Comment by BengaloBongali** [comment]
That's great news! Thanks! I'll look into creating an issue on bountysource about polishing and merging the fuse into Syncthing.
