### ISSUE TITLE
Windows support over Dokan

### ISSUE THREAD

**Issue by merlink01** [burkemw3/syncthingfuse#7]
It would be great to implement Windows Support in the future.

**Comment by burkemw3** [comment]
I am very unlikely to implement this, but anyone is welcome to tackle it.

**Comment by palitu** [comment]
I am going to plus 1 this.  i love the idea of fuse, especially for accessing your files outside of home.  but for me the major places i would use it is on my phone and on a windows machine.

cheers, and good luck!

**Comment by burkemw3** [comment]
I'm going to close this as won't fix as I have no plans to work on it. Others are still welcome to tackle it, and I will work to get those changes merged.
